name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: my-node-app
  GITHUB_USERNAME: falgunitagadkar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
